The ``7-base_geometry`` module
============================

Using ``BaseGeometry``
---------------------

Import function from module:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Correct Class Type test:
    >>> bg = BaseGeometry()
    >>> type(bg) == BaseGeometry
    True


area() instance method
----------------------
area method is an instance method:
    >>> type(BaseGeometry.__dict__['area'])
    <class 'function'>

area with no args:
    >>> bg.__class__.area()
    Traceback (most recent call last):
    TypeError: area() missing 1 required positional argument: 'self'

area method with 1 arg:
    >>> bg.area(10)
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 2 were given

area method:
    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented


integer_validator() instance method
-----------------------------------
integer_validator (type_test):
    >>> type(BaseGeometry.__dict__['integer_validator'])
    <class 'function'>

integer_validator methode with no args:
    >>> bg.__class__.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 3 required positional arguments: 'self', 'name', and 'value'

integer_validator methode with no args:
    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
    
integer_validator methode (test with 3 args):
    >>> bg.integer_validator(1, 1, 1)
    Traceback (most recent call last):
    TypeError: integer_validator() takes 3 positional arguments but 4 were given

integer_validator methode with a string and a float:
    >>> bg.integer_validator("foo", 3.0)
    Traceback (most recent call last):
    TypeError: foo must be an integer

integer_validator methode with a string:
    >>> bg.integer_validator("arg", 3.14)
    Traceback (most recent call last):
    TypeError: arg must be an integer

integer_validator methode using string:
    >>> bg.integer_validator("Bar", "bar")
    Traceback (most recent call last):
    TypeError: Bar must be an integer

integer_validator methode using boolean:
    >>> bg.integer_validator("zar", True)
    Traceback (most recent call last):
    TypeError: zar must be an integer

integer_validator methode using list:
    >>> bg.integer_validator("a", [1])
    Traceback (most recent call last):
    TypeError: a must be an integer

integer_validator method using a string and None:
    >>> bg.integer_validator("Bob", None)
    Traceback (most recent call last):
    TypeError: Bob must be an integer

integer_validator method:
    >>> bg.integer_validator("key", 0)
    Traceback (most recent call last):
    ValueError: key must be greater than 0

integer_validator method negative value:
    >>> bg.integer_validator("key", -900)
    Traceback (most recent call last):
    ValueError: key must be greater than 0

integer_validator method using acceptable value:
    >>> bg.integer_validator("key", 100)
    
integer_validator method using acceptable value:
    >>> bg.integer_validator("key", 50)

integer_validator method usin empty string:
    >>> bg.integer_validator("", 100)

integer_validator method using empty string:
    >>> bg.integer_validator(None, 6)

integer_validator method using tuple:
    >>> bg.integer_validator("Bob", (5, 9))
    Traceback (most recent call last):
    TypeError: Bob must be an integer

integer_validator method using dic:
    >>> bg.integer_validator("Bob", {3, 7})
    Traceback (most recent call last):
    TypeError: Bob must be an integer